service: rss-fetcher-lambda

provider:
  name: aws
  runtime: nodejs20.x
  region: ca-central-1
  environment:
    APP_ID: ${env:APP_ID}
    API_URL: ${env:API_URL}
    API_KEY: ${env:API_KEY}

functions:
  fetchReviews:
    handler: src/handler.fetchReviews
    events:
      - schedule: rate(1 hour)
    timeout: 30