service: rss-fetcher-lambda

provider:
  name: aws
  runtime: nodejs20.x
  region: ca-central-1
  environment:
    APP_ID: '595068606'
    API_URL: 'https://reviews-api-ps6t.onrender.com'
    API_KEY: 'supersecret'

functions:
  fetchReviews:
    handler: src/handler.fetchReviews
    events:
      - schedule: rate(1 hour)
    timeout: 10