services:
  - type: web
    name: review-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-db
          property: connectionString

databases:
  - name: your-db
    plan: free
